# This is a basic workflow to help you get started with Actions

name: Part D

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the main branch
  push:
    branches: [ main ]
    paths:
      - 'a1_partd.py'
      
  pull_request:
    branches: [ main ]
    paths:
      - 'a1_partd.py'

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2
        with:
          path: ./assignment

      - name: Checkout Tester
        uses: actions/checkout@v2
        with:
          repository: seneca-dsa456/testers
          token: ${{ secrets.TESTER_ACCESS }}
          path: ./tester

      - name: Copy python tester files
        run: cp ./tester/test_a1_partd.py ./

      - name: Copy Maze files
        run: cp ./tester/maze.py ./

      - name: Copy Maze files
        run: cp ./tester/maze1.txt ./

      - name: Copy Maze files
        run: cp ./tester/maze2.txt ./

      - name: Copy Maze files
        run: cp ./tester/maze3.txt ./

      - name: Copy assignment files
        run: cp ./assignment/a1_partd.py ./


      # Runs a single command using the runners shell
      - name: Run tester
        run: python test_a1_partd.py


